# Generated by Django 2.2.7 on 2019-11-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='discription',
            new_name='description',
        ),
    ]
