# Generated by Django 2.2.7 on 2019-11-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='ages',
            new_name='max_ages',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='a_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='min_ages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
