# Generated by Django 2.2.7 on 2019-11-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191116_0724'),
        ('api', '0003_auto_20191116_0842'),
    ]

    operations = [
    ]
