# Generated by Django 2.2.7 on 2019-11-16 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_merge_20191116_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='max_ages',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='min_ages',
            new_name='min_age',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity')),
            ],
        ),
    ]
